modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
logoFile="logo.png"

[[mods]]
modId="veggiesdelight"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.veggiesdelight]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.veggiesdelight]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"


[[dependencies.veggiesdelight]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.2.3,)"
    ordering="AFTER"
    side="BOTH"