modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
logoFile="logo.png"

[[mods]]
    modId="veggiesdelight"
    version="${mod_version}"
    displayName="Veggies Delight"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[dependencies.veggiesdelight]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.veggiesdelight]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.veggiesdelight]]
    modId="farmersdelight"
    type="required"
    mandatory=true
    versionRange="[1.2.3,)"
    ordering="AFTER"
    side="BOTH"
